sudo: required

language: nodejs

node:
 - '6'

services:
 - docker

branches:
 except:
 - develop
 - master

before_script:
 - cd ./trollbox/
 - npm install
script:
 - node validate.js

after_success:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker build -f Dockerfile -t gregv8/trollbox:8080 .
 - docker tag gregv8/trollbox:0.1.0 gregv8/trollbox:travis-$TRAVIS_BUILD_NUMBER
 - docker push gregv8/trollbox
 
